// <auto-generated />
using System;
using Betty.databases.guilds;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Betty.Migrations
{
    [DbContext(typeof(GuildDB))]
    [Migration("20190202110818_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Betty.databases.guilds.ApplicationTB", b =>
                {
                    b.Property<ulong>("ApplicationId");

                    b.Property<ulong>("Channel");

                    b.Property<DateTime>("Deadline");

                    b.Property<string>("InviteID")
                        .IsRequired();

                    b.HasKey("ApplicationId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Betty.databases.guilds.EventNotificationTB", b =>
                {
                    b.Property<ulong>("NotificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<ulong>("EventId");

                    b.Property<string>("ResponseKeyword")
                        .IsRequired();

                    b.HasKey("NotificationId");

                    b.HasIndex("EventId");

                    b.ToTable("EventNotifications");
                });

            modelBuilder.Entity("Betty.databases.guilds.EventTB", b =>
                {
                    b.Property<ulong>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<ulong>("GuildId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<ulong?>("NotificationChannel");

                    b.HasKey("EventId");

                    b.HasIndex("GuildId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Betty.databases.guilds.GuildTB", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<ulong?>("Notification");

                    b.Property<ulong?>("Public");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Betty.databases.guilds.ApplicationTB", b =>
                {
                    b.HasOne("Betty.databases.guilds.GuildTB", "Guild")
                        .WithOne("Application")
                        .HasForeignKey("Betty.databases.guilds.ApplicationTB", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Betty.databases.guilds.EventNotificationTB", b =>
                {
                    b.HasOne("Betty.databases.guilds.EventTB", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Betty.databases.guilds.EventTB", b =>
                {
                    b.HasOne("Betty.databases.guilds.GuildTB", "Guild")
                        .WithMany("Events")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
